name: recipes_app
description: "Test Recipes Flutter project."
version: 1.0.0+1

environment:
  sdk: ^3.9.2

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8

  #StateManager
  flutter_bloc: ^9.1.1

  #Routing
  go_router: ^17.0.0
  get_it: ^9.0.5

  #Storage
  shared_preferences: ^2.5.3
  cached_network_image: ^3.4.1

  #Models
  freezed_annotation: ^3.1.0
  json_annotation: ^4.9.0

  #Networking
  dio: ^5.9.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^5.0.0
  build_runner: ^2.10.3
  freezed: ^3.2.3
  json_serializable: ^6.11.1

flutter:
  uses-material-design: true
